language: python

python:
  - 3.8

before_install:
  - export DJANGO_SETTINGS_MODULE=tests.settings

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - make test

after_success:
  - pipenv run coverage html
  - pipenv run coverage report -m
  - pipenv coveralls
