language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO="~=2.2"
  - DJANGO="~=3.0"

before_install:
  - export DJANGO_SETTINGS_MODULE=tests.settings

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install -q "Django${DJANGO}"

script:
  - make test

after_success:
  - pipenv run coverage html
  - pipenv run coverage report -m
  - pipenv coveralls
