language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO="~=2.2"
  - DJANGO="~=3.0"

before_install:
  - export DJANGO_SETTINGS_MODULE=tests.settings

install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --source=jet --omit=*/migrations/*,*/tests/* manage.py test jet

after_success:
  - coverage report
  - coveralls
